"""initial schema

Revision ID: 24b03f427121
Revises: 
Create Date: 2026-04-29 14:20:01.493760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b03f427121'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_budget', sa.Integer(), nullable=False),
    sa.Column('my_budget_remaining', sa.Integer(), nullable=False),
    sa.Column('my_roster', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_nominee_yahoo_id', sa.String(length=50), nullable=True),
    sa.Column('current_bid_amount', sa.Integer(), nullable=True),
    sa.Column('clock_seconds_remaining', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('yahoo_player_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_abbr', sa.String(length=5), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('contract_year', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ceiling_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('floor_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_adjusted_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_value_fantasypros', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_value_sleeper', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_value_underdog', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_value_confidence', sa.String(length=20), nullable=True),
    sa.Column('market_value_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_gap', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('value_gap_signal', sa.String(length=30), nullable=True),
    sa.Column('recommended_bid_ceiling', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('let_go_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('elite_anchor_weight', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('situation_score', sa.String(length=20), nullable=True),
    sa.Column('positional_scarcity_modifier', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('breakout_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_pipeline_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yahoo_player_id')
    )
    op.create_table('team_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_abbr', sa.String(length=5), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('pass_protection_grade', sa.String(length=5), nullable=True),
    sa.Column('run_blocking_grade', sa.String(length=5), nullable=True),
    sa.Column('qb_name', sa.String(length=100), nullable=True),
    sa.Column('qb_tier', sa.String(length=20), nullable=True),
    sa.Column('qb_experience_years', sa.Integer(), nullable=True),
    sa.Column('qb_pressure_performance', sa.String(length=20), nullable=True),
    sa.Column('qb_cpoe', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('qb_air_yards_per_attempt', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('qb_downfield_aggressiveness', sa.String(length=20), nullable=True),
    sa.Column('rookie_qb_flag', sa.Boolean(), nullable=False),
    sa.Column('compound_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('oc_name', sa.String(length=100), nullable=True),
    sa.Column('oc_scheme', sa.String(length=30), nullable=True),
    sa.Column('oc_run_pass_split_tendency', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('personnel_tendency', sa.String(length=10), nullable=True),
    sa.Column('red_zone_philosophy', sa.String(length=20), nullable=True),
    sa.Column('system_ceiling', sa.String(length=20), nullable=True),
    sa.Column('system_grade', sa.String(length=5), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beat_reporter_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opponent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_state_id', sa.UUID(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('yahoo_team_id', sa.String(length=50), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('roster', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_remaining', sa.Integer(), nullable=True),
    sa.Column('budget_spent', sa.Integer(), nullable=True),
    sa.Column('positional_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=True),
    sa.Column('combo_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('apparent_strategy', sa.String(length=30), nullable=True),
    sa.Column('likely_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('management_style', sa.String(length=30), nullable=True),
    sa.Column('current_record', sa.String(length=10), nullable=True),
    sa.Column('trade_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_state_id'], ['draft_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_player_id', sa.UUID(), nullable=True),
    sa.Column('trigger_player_name', sa.String(length=100), nullable=True),
    sa.Column('trigger_condition', sa.String(length=50), nullable=True),
    sa.Column('effect_on_value', sa.String(length=20), nullable=True),
    sa.Column('value_impact_pct', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['trigger_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_injury_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('overall_risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_adjusted_value_modifier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('injury_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pattern_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chronic_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_carry_count', sa.Integer(), nullable=True),
    sa.Column('workload_cliff_flag', sa.Boolean(), nullable=False),
    sa.Column('high_mileage_flag', sa.Boolean(), nullable=False),
    sa.Column('post_acl_flag', sa.Boolean(), nullable=False),
    sa.Column('concussion_count', sa.Integer(), nullable=False),
    sa.Column('recovery_assessment', sa.String(length=30), nullable=True),
    sa.Column('age_risk_multiplier', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('role_classification', sa.String(length=30), nullable=True),
    sa.Column('target_share_3yr_avg', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('target_share_last_season', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('targets_per_route_run', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('air_yards_share', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('snap_percentage', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('separation_score', sa.String(length=20), nullable=True),
    sa.Column('yards_after_catch_score', sa.String(length=20), nullable=True),
    sa.Column('contested_catch_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('efficiency_signal', sa.String(length=20), nullable=True),
    sa.Column('age_curve_position', sa.String(length=20), nullable=True),
    sa.Column('career_trajectory', sa.String(length=20), nullable=True),
    sa.Column('clean_season_baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anomalous_seasons_excluded', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakout_flag', sa.Boolean(), nullable=False),
    sa.Column('breakout_reasoning', sa.Text(), nullable=True),
    sa.Column('positional_scarcity_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('bye_week', sa.Integer(), nullable=True),
    sa.Column('early_window_grade', sa.String(length=20), nullable=True),
    sa.Column('early_window_favorable_weeks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('early_window_tough_weeks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('early_window_summary', sa.Text(), nullable=True),
    sa.Column('full_season_grade', sa.String(length=20), nullable=True),
    sa.Column('playoff_window_grade', sa.String(length=20), nullable=True),
    sa.Column('playoff_weeks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('playoff_matchups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('playoff_summary', sa.Text(), nullable=True),
    sa.Column('weather_risk', sa.String(length=20), nullable=True),
    sa.Column('weather_affected_weeks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('divisional_game_weeks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('schedule_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_roster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('yahoo_team_id', sa.String(length=50), nullable=True),
    sa.Column('acquisition_price', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('acquisition_week', sa.Integer(), nullable=False),
    sa.Column('weekly_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weekly_snap_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weekly_target_share', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_trade_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('value_trend', sa.String(length=20), nullable=True),
    sa.Column('sell_high_flag', sa.Boolean(), nullable=False),
    sa.Column('buy_low_flag', sa.Boolean(), nullable=False),
    sa.Column('injury_concern_flag', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_roster')
    op.drop_table('player_schedules')
    op.drop_table('player_profiles')
    op.drop_table('player_injury_profiles')
    op.drop_table('player_dependencies')
    op.drop_table('opponent_profiles')
    op.drop_table('beat_reporter_signals')
    op.drop_table('team_systems')
    op.drop_table('players')
    op.drop_table('draft_state')
    # ### end Alembic commands ###
