"""add_valuation_agent_columns_to_players

Revision ID: 7e1af623cb4b
Revises: 7f6226abf5e4
Create Date: 2026-05-08 07:54:53.204370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1af623cb4b'
down_revision: Union[str, None] = '7f6226abf5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('ai_bid_ceiling', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ai_confidence_floor', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('ai_confidence_ceiling', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('value_assessment', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('auction_note', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('pay_up_flag', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('players', sa.Column('nomination_target_flag', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'nomination_target_flag')
    op.drop_column('players', 'pay_up_flag')
    op.drop_column('players', 'auction_note')
    op.drop_column('players', 'value_assessment')
    op.drop_column('players', 'ai_confidence_ceiling')
    op.drop_column('players', 'ai_confidence_floor')
    op.drop_column('players', 'ai_bid_ceiling')
    # ### end Alembic commands ###
