"""add projection_reasoning to player_profiles

Revision ID: 7f6226abf5e4
Revises: 4bde60987b65
Create Date: 2026-05-07 14:49:59.219412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6226abf5e4'
down_revision: Union[str, None] = '4bde60987b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_profiles', sa.Column('projection_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_profiles', 'projection_reasoning')
    # ### end Alembic commands ###
